import { requireChatGPTUser } from "../chatgpt-auth";
import { authorizeAdmin } from "../../db/admin";
import PylonCalibration from "./PylonCalibration";

export const dynamic = "force-dynamic";

type Assessment = { id:string; postcode:string; address:string; annual_usage_kwh:number; usage_source:string; panel_count:number; annual_generation_kwh:number; annual_bill_before:number; annual_bill_solar_battery:number; annual_benefit:number; created_at:string };
type Lead = { customer_name:string; phone:string; email:string; preferred_time:string; address:string|null; created_at:string };
type Comparison = { address:string; proposal_url:string; our_usage:number; pylon_usage:number; our_panels:number; pylon_panels:number; our_generation:number; pylon_generation:number; our_before:number; pylon_before:number; our_after:number; pylon_after:number; our_benefit:number; pylon_benefit:number; input_hit_rate:number; generation_hit_rate:number; benefit_hit_rate:number; overall_hit_rate:number; created_at:string };
type ApiUsage = { provider:string; period_calls:number; total_calls:number; failed_calls:number; last_call:string };
type DailyActivity = { day:string; assessments:number };

const pounds = (value:number) => new Intl.NumberFormat("en-GB", { style:"currency", currency:"GBP", maximumFractionDigits:0 }).format(value);
const delta = (ours:number, pylon:number, unit="") => `${ours-pylon>=0?"+":""}${(ours-pylon).toLocaleString("en-GB",{maximumFractionDigits:1})}${unit}`;
const conservatism = (ours:number, pylon:number) => pylon ? (pylon-ours)/Math.abs(pylon)*100 : 0;
function ConservativeBadge({ ours, pylon }: { ours:number; pylon:number }) {
  const value=conservatism(ours,pylon);
  const tone=value>15?"review":value>=5?"good":value>=-5?"close":"optimistic";
  const label=value>15?"Needs review":value>=5?"Reasonably conservative":value>=-5?"Close to Pylon":"More optimistic";
  return <span className={`conservative-badge ${tone}`}><b>{value>=0?"+":""}{value.toFixed(1)}%</b> {label}</span>;
}

export default async function AdminPage({ searchParams }: { searchParams?:Promise<{period?:string}> }) {
  const user = await requireChatGPTUser("/admin");
  const { allowed, db } = await authorizeAdmin(user, true);
  if (!allowed) return <main className="admin-denied"><h1>Admin access required</h1><p>This dashboard contains customer contact information.</p></main>;
  const requested=(await searchParams)?.period;
  const period=requested==="day"||requested==="week"||requested==="month"||requested==="all"?requested:"week";
  const periods={day:{label:"Today",where:"created_at >= datetime('now','-1 day')"},week:{label:"Last 7 days",where:"created_at >= datetime('now','-7 days')"},month:{label:"Last 30 days",where:"created_at >= datetime('now','-30 days')"},all:{label:"All time",where:"1=1"}} as const;
  const where=periods[period].where;
  const [periodSummary,allSummary,assessmentsResult,leadsResult,comparisonsResult,apiResult,activityResult]=await Promise.all([
    db.prepare(`SELECT COUNT(*) assessments,COUNT(DISTINCT postcode) postcodes,COUNT(DISTINCT address) addresses,(SELECT COUNT(*) FROM leads WHERE ${where}) leads FROM assessments WHERE ${where}`).first<Record<string,number>>(),
    db.prepare(`SELECT COUNT(*) assessments,COUNT(DISTINCT address) addresses,(SELECT COUNT(*) FROM leads) leads FROM assessments`).first<Record<string,number>>(),
    db.prepare(`SELECT * FROM assessments ORDER BY created_at DESC LIMIT 100`).all<Assessment>(),
    db.prepare(`SELECT l.customer_name,l.phone,l.email,l.preferred_time,a.address,l.created_at FROM leads l LEFT JOIN assessments a ON a.id=l.assessment_id ORDER BY l.created_at DESC LIMIT 100`).all<Lead>(),
    db.prepare(`SELECT a.address,p.proposal_url,a.annual_usage_kwh our_usage,p.pylon_annual_usage_kwh pylon_usage,a.panel_count our_panels,p.pylon_panel_count pylon_panels,a.annual_generation_kwh our_generation,p.pylon_generation_kwh pylon_generation,a.annual_bill_before our_before,p.pylon_bill_before pylon_before,a.annual_bill_solar_battery our_after,p.pylon_bill_after pylon_after,a.annual_benefit our_benefit,(p.pylon_bill_before-p.pylon_bill_after) pylon_benefit,p.input_hit_rate,p.generation_hit_rate,p.benefit_hit_rate,p.overall_hit_rate,p.created_at FROM pylon_comparisons p JOIN (SELECT assessment_id,proposal_url,MAX(rowid) latest_rowid FROM pylon_comparisons GROUP BY assessment_id,proposal_url) latest ON latest.latest_rowid=p.rowid JOIN assessments a ON a.id=p.assessment_id ORDER BY p.created_at DESC LIMIT 100`).all<Comparison>(),
    db.prepare(`SELECT provider,SUM(CASE WHEN ${where} THEN 1 ELSE 0 END) period_calls,COUNT(*) total_calls,SUM(CASE WHEN success=0 THEN 1 ELSE 0 END) failed_calls,MAX(created_at) last_call FROM api_usage_events GROUP BY provider ORDER BY period_calls DESC,total_calls DESC`).all<ApiUsage>(),
    db.prepare(`SELECT date(created_at) day,COUNT(*) assessments FROM assessments WHERE created_at >= datetime('now','-30 days') GROUP BY date(created_at) ORDER BY day`).all<DailyActivity>(),
  ]);
  const assessments=assessmentsResult.results as Assessment[],comparisons=comparisonsResult.results as Comparison[],activity=activityResult.results as DailyActivity[],apiUsage=apiResult.results as ApiUsage[],leads=leadsResult.results as Lead[];
  const average=(key:keyof Comparison)=>comparisons.length?comparisons.reduce((sum,item)=>sum+Number(item[key]||0),0)/comparisons.length:0;
  const maxActivity=Math.max(...activity.map(item=>item.assessments),1);
  const conversion=(periodSummary?.assessments??0)>0?(periodSummary?.leads??0)/(periodSummary?.assessments??1)*100:0;
  return <main className="admin-shell">
    <header><div><span>APOLLOGRID · OPERATIONS</span><h1>Assessment operations</h1><p>Demand, API usage, model calibration and customer records in one place.</p></div><div className="admin-actions"><a className="export" href="/api/admin/export">↓ Export Excel</a><a href="/">Open calculator →</a></div></header>
    <nav className="period-tabs" aria-label="Dashboard period">{Object.entries(periods).map(([key,value])=><a className={period===key?"active":""} href={`/admin?period=${key}`} key={key}>{value.label}</a>)}</nav>
    <section className="admin-stats"><div><small>Assessments · {periods[period].label}</small><strong>{periodSummary?.assessments??0}</strong><em>{allSummary?.assessments??0} all time</em></div><div><small>Unique addresses</small><strong>{periodSummary?.addresses??0}</strong><em>{allSummary?.addresses??0} all time</em></div><div><small>Customer leads</small><strong>{periodSummary?.leads??0}</strong><em>{allSummary?.leads??0} all time</em></div><div><small>Lead conversion</small><strong>{conversion.toFixed(1)}%</strong><em>leads ÷ assessments</em></div></section>
    <section className="dashboard-row"><div className="activity-panel"><div className="admin-panel-title"><span>30-day activity</span><h2>Assessments by day</h2></div>{activity.length?<div className="activity-chart">{activity.map(item=><div key={item.day} title={`${item.day}: ${item.assessments} assessments`}><i style={{height:`${Math.max(item.assessments/maxActivity*100,8)}%`}}/><small>{item.day.slice(5)}</small></div>)}</div>:<p className="empty">Activity will appear after assessments are completed.</p>}</div><div className="api-panel"><div className="admin-panel-title"><span>API quota monitor</span><h2>External API calls</h2><p>Counts begin from this dashboard version. Restarting the website does not reset vendor quotas.</p></div><div className="api-list">{apiUsage.length?apiUsage.map(item=><div key={item.provider}><b>{item.provider}</b><span><strong>{item.period_calls}</strong> this period</span><span>{item.total_calls} total</span><em className={item.failed_calls?"warn":""}>{item.failed_calls} failed</em><small>{item.last_call?new Date(item.last_call).toLocaleString("en-GB"):"—"}</small></div>):<p className="empty">No tracked API calls yet.</p>}</div></div></section>
    <section className="calibration-zone"><div className="zone-heading"><div><span>MODEL CALIBRATION</span><h2>Our model compared with Pylon</h2><p>Parse a proposal, save it against the same address, then inspect exact differences—not only a blended score.</p></div><div className="hit-pills"><span>Input <b>{average("input_hit_rate").toFixed(1)}%</b></span><span>Generation <b>{average("generation_hit_rate").toFixed(1)}%</b></span><span>Benefit <b>{average("benefit_hit_rate").toFixed(1)}%</b></span><strong>Overall {average("overall_hit_rate").toFixed(1)}%</strong></div></div><PylonCalibration assessments={assessments.map(({id,address,created_at})=>({id,address,created_at}))}/>{comparisons.length?<div className="comparison-dashboard">{comparisons.map((item,index)=><article key={`${item.address}-${index}`}><header><div><b>{item.address}</b><small>{new Date(item.created_at).toLocaleDateString("en-GB")}</small></div>{item.proposal_url&&<a href={item.proposal_url} target="_blank" rel="noreferrer">Open proposal ↗</a>}<strong>{item.overall_hit_rate.toFixed(1)}%</strong></header><div className="conservatism-strip"><div><small>Generation conservatism</small><ConservativeBadge ours={item.our_generation} pylon={item.pylon_generation}/></div><div><small>Benefit conservatism</small><ConservativeBadge ours={item.our_benefit} pylon={item.pylon_benefit}/></div></div><div className="comparison-metrics"><div><small>Annual use</small><span>Ours <b>{item.our_usage.toLocaleString()} kWh</b></span><span>Pylon <b>{item.pylon_usage.toLocaleString()} kWh</b></span><em>{delta(item.our_usage,item.pylon_usage," kWh")}</em></div><div><small>Panels</small><span>Ours <b>{item.our_panels}</b></span><span>Pylon <b>{item.pylon_panels}</b></span><em>{delta(item.our_panels,item.pylon_panels)}</em></div><div><small>Annual generation</small><span>Ours <b>{item.our_generation.toLocaleString()} kWh</b></span><span>Pylon <b>{item.pylon_generation.toLocaleString()} kWh</b></span><em>{delta(item.our_generation,item.pylon_generation," kWh")}</em></div><div><small>Bill after</small><span>Ours <b>{pounds(item.our_after)}</b></span><span>Pylon <b>{pounds(item.pylon_after)}</b></span><em>{pounds(item.our_after-item.pylon_after)}</em></div><div><small>First-year benefit</small><span>Ours <b>{pounds(item.our_benefit)}</b></span><span>Pylon <b>{pounds(item.pylon_benefit)}</b></span><em>{pounds(item.our_benefit-item.pylon_benefit)}</em></div></div><footer><span>Input {item.input_hit_rate.toFixed(0)}%</span><span>Generation {item.generation_hit_rate.toFixed(0)}%</span><span>Benefit {item.benefit_hit_rate.toFixed(0)}%</span></footer></article>)}</div>:<p className="calibration-empty-state">No saved comparison yet. Paste a Pylon proposal link above and parse it.</p>}</section>
    <section className="admin-panel"><div className="admin-panel-title"><span>Assessment records</span><h2>Latest calculations</h2></div><div className="admin-table-wrap"><table><thead><tr><th>Date</th><th>Address</th><th>Use</th><th>Panels</th><th>Generation</th><th>Before</th><th>After</th><th>Benefit</th></tr></thead><tbody>{assessments.map(item=><tr key={item.id}><td>{new Date(item.created_at).toLocaleString("en-GB")}</td><td><b>{item.address}</b><small>{item.postcode} · {item.usage_source}</small></td><td>{item.annual_usage_kwh.toLocaleString()} kWh</td><td>{item.panel_count}</td><td>{item.annual_generation_kwh.toLocaleString()} kWh</td><td>{pounds(item.annual_bill_before)}</td><td>{pounds(item.annual_bill_solar_battery)}</td><td className="positive">{pounds(item.annual_benefit)}</td></tr>)}</tbody></table></div></section>
    <section className="admin-panel"><div className="admin-panel-title"><span>Customer records</span><h2>Contact requests</h2></div>{leads.length?leads.map((lead,index)=><article className="lead-row" key={`${lead.email}-${index}`}><div><b>{lead.customer_name}</b><small>{lead.address??"Unlinked assessment"}</small></div><div><a href={`mailto:${lead.email}`}>{lead.email}</a><a href={`tel:${lead.phone}`}>{lead.phone}</a></div><span>{lead.preferred_time||"No preferred time"}</span></article>):<p className="empty">No customer details submitted yet.</p>}</section>
    <footer>Hit-rate weighting: 20% matched inputs + 40% annual generation + 40% first-year benefit. Excel export includes assessments, leads, Pylon comparisons and API usage.</footer>
  </main>;
}
