'use client';
import {useEffect,useState} from 'react';
import type {Member} from '@/lib/access';
import {Locale,Lang,errorText,roleLabels} from '@/lib/i18n';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import RoadShow from './road-show';
import TeamPanel from './team-panel';
type Invitation={role:number;store:string;leader:string;target:string|null;expires:number};
export default function Portal(){
 const [lang,setLang]=useState<Lang>('en'),[user,setUser]=useState<Member|null>(null),[required,setRequired]=useState(false),[ready,setReady]=useState(false),[mode,setMode]=useState('register'),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[panel,setPanel]=useState(false),[token,setToken]=useState(''),[invitation,setInvitation]=useState<Invitation|null>(null);
 const t=(zh:string,en:string)=>lang==='zh'?zh:en;
 async function request(data:unknown){const r=await fetch('/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json() as Record<string,unknown>;if(!r.ok)throw new Error(String(d.error));return d;}
 useEffect(()=>{const l=localStorage.getItem('road-lang');setLang(l==='zh'||l==='en'?l:navigator.language.startsWith('zh')?'zh':'en');const code=new URLSearchParams(location.hash.slice(1)).get('invite')||'';setToken(code);
  void(async()=>{try{const r=await fetch('/api/access',{cache:'no-store'});const d=await r.json() as {user:Member|null;qrRequired:boolean;error?:string};if(!r.ok)throw new Error(d.error);setUser(d.user);setRequired(d.qrRequired);if(code){const i=await request({action:'inspect',token:code}) as unknown as Invitation;setInvitation(i);setName(i.target||'');}}catch(e){setError(e instanceof Error?e.message:'unavailable');}finally{setReady(true);}})();
 },[]);
 useEffect(()=>{document.documentElement.lang=lang==='zh'?'zh-CN':'en';},[lang]);
 async function enter(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const d=await request({action:invitation?'register':mode,name,token:invitation?token:undefined});setUser(d.user as Member);setInvitation(null);setToken('');history.replaceState(null,'',location.pathname);}catch(e){setError(e instanceof Error?e.message:'unavailable');}finally{setBusy(false);}}
 async function logout(){if(user){try{const cached=JSON.parse(localStorage.getItem(`road-show-v1:${user.id}`)||'{}');if(cached.records?.some((r:{dirty:boolean})=>r.dirty)&&!confirm(t('还有未同步数据，仍要退出？记录保留在本机。','Unsynced records remain on this browser. Sign out anyway?')))return;}catch{}}
  await request({action:'logout'});if(user?.role===0){location.href='/signout-with-chatgpt?return_to=%2F';return;}setUser(null);setPanel(false);setName('');
 }
 return <Locale.Provider value={lang}><div className="portal-tools"><a href="https://apollogridtest.online" className="apollo-brand">APOLLO<span>GRID</span></a><div><button className="quiet" onClick={()=>{const l=lang==='zh'?'en':'zh';setLang(l);localStorage.setItem('road-lang',l);}}>{lang==='zh'?'EN':'中文'}</button>{user&&<><span className="identity">{user.name} · {roleLabels[user.role][lang==='zh'?0:1]}</span>{user.role<3&&<button className="outline" onClick={()=>setPanel(!panel)}>{panel?t('现场采集','Field collection'):t('账户管理','Team management')}</button>}<button className="quiet" onClick={()=>void logout()}>{t('退出','Sign out')}</button></>}</div></div>
 {!ready?<main className="workspace empty">{t('正在读取账户…','Loading account…')}</main>:user&&!invitation?<>{panel?<TeamPanel user={user}/>:<RoadShow owner={user.id} member={user}/>}</>:<main className="entry-layout"><section className="entry-story"><p className="eyebrow">ROAD SHOW EXPERIMENT</p><h1>{t('把每一次对话，\n变成下一步。','Every conversation.\nA step forward.')}</h1><p>{t('现场计数、随时补录、自动保存。','Count in the field. Revisit any step. Save as you go.')}</p><div className="entry-steps"><span>01 · {t('进入','Join')}</span><span>02 · {t('采集','Collect')}</span><span>03 · {t('回顾','Review')}</span></div></section><section className="card entry-card"><p className="eyebrow">APOLLOGRID / ROAD SHOW</p><h2>{t('开始现场记录','Start your field record')}</h2>
 {invitation?<div className="notice"><b>{t('邀请已验证','Invitation validated')}</b><p>{roleLabels[invitation.role][lang==='zh'?0:1]} · {invitation.store}</p><p>{t('直属领导','Supervisor')}: {invitation.leader}</p>{invitation.target&&<p>{t('恢复账户','Recover account')}: {invitation.target}</p>}</div>:!required?<Tabs value={mode} onValueChange={v=>{setMode(v);setError('');}}><TabsList className="step-tabs"><TabsTrigger value="register">{t('首次使用','First visit')}</TabsTrigger><TabsTrigger value="login">{t('已有账户','Returning member')}</TabsTrigger></TabsList></Tabs>:<div className="notice">{t('请扫描直属领导发出的邀请二维码。如需在新设备登录，请向上级获取恢复邀请。','Scan your supervisor’s invitation QR. To sign in on a new device, ask for a recovery invitation.')}</div>}
 <form onSubmit={enter}><label>{t('英文名','English name')}<input autoComplete="username" autoCapitalize="words" maxLength={90} value={name} onChange={e=>setName(e.target.value)} placeholder={t('请输入你在公司使用的英文名','Enter the English name you use at work')} required readOnly={Boolean(invitation?.target)}/></label><p className="muted small-note">{t('用于识别并归档你的现场记录','Used to identify and organise your field records')}</p>{error&&<p className="notice error" role="alert">{errorText(error,lang)}</p>}<button className="primary" type="submit" disabled={busy||(required&&!invitation)}>{busy?t('正在进入…','Please wait…'):t('继续，进入现场采集','Continue to field collection')}</button></form><p className="muted small-note">{t('重名请使用 英文名_直属领导英文名，例如 Mia_Alex。','If a name is taken, use Name_LeaderName, e.g. Mia_Alex.')}</p><a className="admin-link" href="/admin-entry" target="_top">{t('0 号管理员登录','Owner sign-in')}</a></section></main>}
 </Locale.Provider>;
}
