'use client';
import {useContext,useEffect,useRef,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Plus,Minus,Download,ArrowRight,ArrowLeft,Check,Cloud,RefreshCw} from 'lucide-react';
import {categories,freshRecord,recordSchema,total,type LocalRecord,type CounterKey} from '@/lib/records';
import {exportExcel} from '@/lib/excel';
import type {Member} from '@/lib/access';
import {Locale,useText,errorText} from '@/lib/i18n';

export default function RoadShow({owner,member}:{owner:string;member:Member}){
 const lang=useContext(Locale),t=useText();
 const [records,setRecords]=useState<LocalRecord[]>([]),[current,setCurrent]=useState(''),[view,setView]=useState('field'),[step,setStep]=useState('0'),[ready,setReady]=useState(false),[syncState,setSyncState]=useState('loading'),[notice,setNotice]=useState(''),[storageError,setStorageError]=useState(false),[filter,setFilter]=useState('');
 const rows=useRef<LocalRecord[]>([]),selected=useRef(''),busy=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),loadFailed=useRef(false);
 const key=`road-show-v1:${owner}`;
 function save(next:LocalRecord[]){rows.current=next;setRecords(next);if(loadFailed.current)return;try{localStorage.setItem(key,JSON.stringify({records:next,current:selected.current}));setStorageError(false);}catch{setStorageError(true);}}
 function choose(id:string){selected.current=id;setCurrent(id);setStep('0');setView('field');save(rows.current);}
 function update(patch:Partial<LocalRecord>){save(rows.current.map(r=>r.id===selected.current?{...r,...patch,dirty:true,mutation:crypto.randomUUID(),updatedAt:new Date().toISOString()}:r));setSyncState(navigator.onLine?'pending':'offline');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void sync(),650);}
 async function sync(){
  if(busy.current||loadFailed.current)return;if(!navigator.onLine){setSyncState('offline');return;}busy.current=true;setSyncState('syncing');
  try{
   const removed=new Set<string>();
   for(const snapshot of rows.current.filter(r=>r.dirty)){
    const response=await fetch('/api/records',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({record:snapshot,revision:snapshot.revision,mutation:snapshot.mutation}),signal:AbortSignal.timeout(12000)});
    if(response.status===409){const old=rows.current.find(r=>r.id===snapshot.id)!;const copy={...old,id:crypto.randomUUID(),ownerId:owner,ownerName:member.name,name:`${old.name.slice(0,170)} · Conflict / 冲突副本`,revision:0,mutation:crypto.randomUUID(),dirty:true};if(selected.current===old.id){selected.current=copy.id;setCurrent(copy.id);}save(rows.current.map(r=>r.id===old.id?copy:r));setNotice('conflict');continue;}
    const result=await response.json() as {revision:number;error?:string};
    if(!response.ok){if(response.status===403){removed.add(snapshot.id);setNotice('scopeChanged');continue;}throw new Error(result.error||'unavailable');}
    save(rows.current.map(r=>r.id===snapshot.id?{...r,revision:result.revision,dirty:r.mutation!==snapshot.mutation}:r));
   }
   const response=await fetch('/api/records',{cache:'no-store',signal:AbortSignal.timeout(12000)});const data=await response.json() as {records:LocalRecord[];error?:string};if(!response.ok)throw new Error(data.error||'unavailable');
   // Drop cached records no longer in this account's server-authorised scope.
   const allowed=new Set(data.records.map(r=>r.id));const merged=rows.current.filter(r=>!removed.has(r.id)&&(allowed.has(r.id)||(r.dirty&&(!r.ownerId||r.ownerId===owner)&&r.revision===0)));
   for(const remote of data.records){const i=merged.findIndex(r=>r.id===remote.id);if(i<0)merged.push(remote);else if(!merged[i].dirty)merged[i]=remote;}
   save(merged.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)));setSyncState(merged.some(r=>r.dirty)?'pending':'synced');
  }catch(e){setSyncState(e instanceof Error&&e.message==='loginRequired'?'loginRequired':'unavailable');}finally{busy.current=false;}
 }
 useEffect(()=>{try{const saved=localStorage.getItem(key);if(saved){const data=JSON.parse(saved);if(!Array.isArray(data.records)||!data.records.every((r:LocalRecord)=>recordSchema.safeParse(r).success))throw new Error();rows.current=data.records;setRecords(data.records);selected.current=data.current||data.records[0]?.id||'';setCurrent(selected.current);}}catch{loadFailed.current=true;setStorageError(true);}setReady(true);void sync();const online=()=>void sync(),offline=()=>setSyncState('offline');const interval=setInterval(online,15000);window.addEventListener('online',online);window.addEventListener('offline',offline);return()=>{clearInterval(interval);if(timer.current)clearTimeout(timer.current);window.removeEventListener('online',online);window.removeEventListener('offline',offline);};},[key]);
 const record=records.find(r=>r.id===current);const visible=records.filter(r=>`${r.name} ${r.date} ${r.ownerName||''}`.toLowerCase().includes(filter.toLowerCase()));
 function newRecord(){const r={...freshRecord(),name:lang==='zh'?'路演现场':'Road show',ownerId:owner,ownerName:member.name};selected.current=r.id;setCurrent(r.id);setStep('0');setView('field');save([r,...rows.current]);void sync();}
 function count(k:CounterKey,c:typeof categories[number],delta:number){const r=rows.current.find(r=>r.id===selected.current);if(r)update({[k]:{...r[k],[c]:Math.min(999999,Math.max(0,r[k][c]+delta))}});}
 const counters=(k:CounterKey)=><div className="counters">{categories.map(c=><div className="counter" key={c}><span>{c}</span><button aria-label={`${k} ${c} minus`} disabled={!record?.[k][c]} onClick={()=>count(k,c,-1)}><Minus size={20}/></button><strong aria-live="polite">{record?.[k][c]||0}</strong><button className="plus" aria-label={`${k} ${c} plus`} onClick={()=>count(k,c,1)}><Plus size={23}/></button></div>)}</div>;
 const sums=(k:CounterKey)=>visible.reduce((s,r)=>s+total(r,k),0);
 const status:Record<string,string>={loading:t('正在读取…','Loading…'),pending:t('已存本机 · 待同步','Saved locally · pending'),offline:t('离线 · 已存本机','Offline · saved locally'),syncing:t('正在同步…','Syncing…'),synced:t('云端已同步','Cloud synced'),unavailable:t('同步暂不可用 · 待重试','Sync unavailable · will retry'),loginRequired:errorText('loginRequired',lang)};
 return <div className="app-shell"><header className="topbar"><div className="brand"><div><b>Road Show</b><small>EXPERIMENT</small></div></div><div className="top-actions"><button className="quiet" onClick={()=>void sync()}><Cloud size={17}/><span>{status[syncState]}</span></button><button className="outline" onClick={()=>setView(view==='field'?'admin':'field')}>{view==='field'?t('数据后台','Records'):t('现场采集','Field collection')}</button></div></header>
 <main className={view==='field'?'workspace field':'workspace'}>
 {storageError&&<div className="notice error" role="alert">{t('本机保存不可用或旧缓存异常。请导出备份，勿关闭页面。','Local saving unavailable or cache damaged. Export a backup before closing.')}</div>}
 {notice&&<div className="notice" role="status">{notice==='conflict'?t('另一设备修改了同一场，已保留你的冲突副本。','Another device edited this record. Your changes were kept in a conflict copy.'):notice==='scopeChanged'?t('部分账户权限已变更，已刷新可见数据范围。','Access changed for some accounts. Your visible records have been refreshed.'):t('本场已完成，仍可返回补录或新建下一场。','Session complete. You can still edit it or start a new session.')}<button onClick={()=>setNotice('')}>{t('知道了','Dismiss')}</button></div>}
 {syncState==='loginRequired'&&<div className="notice error"><a href="/">{t('重新进入（未同步草稿保留）','Sign in again (local drafts are kept)')}</a></div>}
 {!ready?<div className="empty">{t('正在读取本机记录…','Loading local records…')}</div>:view==='field'?<>
 <div className="page-heading"><div><p className="eyebrow">FIELD COLLECTION</p><h1>{t('现场实验记录','Field experiment')}</h1></div><button className="outline" onClick={newRecord}><Plus size={18}/>{t('新建场次','New session')}</button></div>
 {!record?<section className="card empty"><h2>{t('准备好，开始第一场','Ready for your next conversation')}</h2><p>{t('记录现场反馈，数据自动保存。','Capture feedback as it happens. Your work saves automatically.')}</p><button className="primary" onClick={newRecord}>{t('新建场次','New session')}<ArrowRight size={18}/></button></section>:<>
 <section className="card event-card"><div className="event-inputs"><label>{t('场次名称','Session name')}<input maxLength={200} value={record.name} onChange={e=>update({name:e.target.value})} placeholder={t('例如：伦敦 · 上午场','e.g. London · morning')}/></label><label>{t('实验日期','Date')}<input type="date" value={record.date} onChange={e=>e.target.value&&update({date:e.target.value})}/></label></div><div className="record-meta"><span className="pill">{record.complete?t('已完成 · 可补录','Complete · editable'):t('进行中','In progress')}</span><span>{record.ownerName||member.name} · {record.dirty?t('已存本机 · 待同步','Saved locally · pending'):t('已同步','Synced')}</span></div></section>
 <Tabs value={step} onValueChange={setStep}><TabsList className="step-tabs">{['Step 1','Step 2–3','Step 4',t('其他','Other')].map((s,i)=><TabsTrigger key={i} value={String(i)} disabled={i>0&&!record.unlocked}>{s}</TabsTrigger>)}</TabsList><p className="step-hint">{record.unlocked?t('点击任意步骤返回补录，已有数据保留。','Return to any step to add details. Previous entries are kept.'):t('保存 Step 1 后即可自由切换。','Save Step 1 to unlock all steps.')}</p>
 <TabsContent value="0">{(['s1a','s1b'] as const).map((k,i)=><section className="card" key={k}><div className="section-title"><span className="number">0{i+1}</span><h2>Sentence {i+1}</h2><span className="count-label">{total(record,k)} {t('次','counts')}</span></div><label className="input-label">{t('现场话术','Opening line')}<textarea rows={2} maxLength={5000} value={i===0?record.sentence1:record.sentence2} onChange={e=>update(i===0?{sentence1:e.target.value}:{sentence2:e.target.value})} placeholder={t('输入现场话术…','Enter your opening line…')}/></label>{counters(k)}</section>)}</TabsContent>
 <TabsContent value="1"><section className="card"><div className="section-title"><h2>Step 2–3 · {t('计数','Counts')}</h2></div>{counters('s23')}</section></TabsContent>
 <TabsContent value="2"><section className="card"><div className="section-title"><h2>Step 4 · {t('计数','Counts')}</h2></div>{counters('s4')}<label className="input-label detail">{t('详细记录','Details')}<textarea rows={5} maxLength={10000} value={record.detail} onChange={e=>update({detail:e.target.value})} placeholder={t('反馈、问题和细节…','Feedback, questions and details…')}/></label></section></TabsContent>
 <TabsContent value="3"><section className="card"><div className="section-title"><h2>{t('其他观察','Other observations')}</h2></div><label className="input-label">{t('补充备注','Notes')}<textarea rows={8} maxLength={10000} value={record.other} onChange={e=>update({other:e.target.value})} placeholder={t('记录其他现场观察…','Any other observations…')}/></label></section></TabsContent></Tabs>
 <footer className="savebar">{Number(step)>0&&<button className="outline" onClick={()=>setStep(String(Number(step)-1))}><ArrowLeft size={17}/>{t('上一步','Back')}</button>}<button className="primary" onClick={()=>{if(step==='0')update({unlocked:true});if(Number(step)<3)setStep(String(Number(step)+1));else{update({complete:true});setNotice('complete');}void sync();}}>{step==='3'?<><Check size={18}/>{t('完成本场记录','Complete session')}</>:<>{t('保存并进入下一步','Save & next step')}<ArrowRight size={18}/></>}</button></footer>
 </>}</>:<>
 <div className="page-heading"><div><p className="eyebrow">EXPERIMENT RECORDS</p><h1>{member.role===3?t('我的历史记录','My history'):t('现场数据后台','Field records')}</h1><p className="muted">{member.role===3?t('仅显示自己的记录','Only your own records'):t('显示你的管理范围内记录','Records within your management scope')}</p></div><button className="primary" disabled={!visible.length} onClick={()=>exportExcel(visible,lang)}><Download size={18}/>{t('导出 Excel','Export Excel')}</button></div>
 {member.role<3&&<><div className="stats"><section className="card"><span>{t('实验场次','Sessions')}</span><strong>{visible.length}</strong></section><section className="card"><span>{t('已完成','Completed')}</span><strong>{visible.filter(r=>r.complete).length}</strong></section><section className="card"><span>{t('本机待同步','Pending on this device')}</span><strong>{visible.filter(r=>r.dirty).length}</strong></section></div><section className="card"><h2>{t('各步骤计数','Counts by step')}</h2><div className="bars">{(['s1a','s1b','s23','s4'] as CounterKey[]).map((k,i)=><div className="bar-row" key={k}><span>{['S1 · 1','S1 · 2','Step 2–3','Step 4'][i]}</span><div className="track"><div style={{width:`${sums(k)/Math.max(1,...(['s1a','s1b','s23','s4'] as CounterKey[]).map(sums))*100}%`}}/></div><b>{sums(k)}</b></div>)}</div><p className="muted small-note">{t('计数不自动视为去重 Leads。','Counts are not deduplicated leads.')}</p></section></>}
 <section className="card"><div className="table-heading"><h2>{t('历史记录','Session history')}</h2><div className="table-actions"><input aria-label={t('筛选记录','Filter records')} placeholder={t('搜索场次、人员或日期','Search session, member or date')} value={filter} onChange={e=>setFilter(e.target.value)}/><button className="outline" onClick={()=>void sync()} aria-label="Refresh"><RefreshCw size={17}/></button></div></div><Table><TableHeader><TableRow>{[t('人员 / 场次','Member / session'),'S1 · 1','S1 · 2','Step 2–3','Step 4',t('状态','Status'),t('保存','Saved'),t('操作','Actions')].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{visible.map(r=><TableRow key={r.id}><TableCell><b>{r.name||t('未命名','Untitled')}</b><div className="muted">{r.ownerName||member.name} · {r.date}</div></TableCell>{(['s1a','s1b','s23','s4'] as CounterKey[]).map(k=><TableCell key={k}>{total(r,k)}</TableCell>)}<TableCell><span className="pill">{r.complete?t('已完成','Complete'):t('进行中','In progress')}</span></TableCell><TableCell>{r.dirty?t('待同步','Pending'):t('已同步','Synced')}</TableCell><TableCell><button className="text-button" onClick={()=>choose(r.id)}>{t('查看 / 补录','View / edit')}</button></TableCell></TableRow>)}</TableBody></Table>{!visible.length&&<p className="empty">{t('暂无记录','No records yet')}</p>}<p className="muted small-note">{t('Excel 导出当前筛选结果，包含场次记录和计数明细两张表。','Excel exports the current filter into Sessions and Counts worksheets.')}</p></section>
 </>}
 </main><div className="app-foot">APOLLOGRID · ROAD SHOW EXPERIMENT</div></div>;
}
