'use client';
import {useContext,useEffect,useState} from 'react';
import QRCode from 'qrcode';
import type {Member} from '@/lib/access';
import {Locale,useText,errorText,roleLabels} from '@/lib/i18n';
import {Switch} from '@/components/ui/switch';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
type Invite={hash:string;role:number;store:string;target:string|null;expires:number;used_by:string|null;revoked:number};
export default function TeamPanel({user}:{user:Member}){
 const t=useText(),lang=useContext(Locale);const [members,setMembers]=useState<Member[]>([]),[invitations,setInvitations]=useState<Invite[]>([]),[required,setRequired]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[store,setStore]=useState(''),[qr,setQr]=useState(''),[link,setLink]=useState(''),[info,setInfo]=useState('');
 async function reload(){const r=await fetch('/api/team',{cache:'no-store'});const d=await r.json() as {members:Member[];invitations:Invite[];qrRequired:boolean;error?:string};if(!r.ok)throw new Error(d.error);setMembers(d.members);setInvitations(d.invitations);setRequired(d.qrRequired);}
 useEffect(()=>{void reload().catch(e=>setError(e.message));},[]);
 async function act(data:unknown){setBusy(true);setError('');try{const r=await fetch('/api/team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json() as {token?:string;expires?:number;error?:string};if(!r.ok)throw new Error(d.error);await reload();return d;}catch(e){setError(e instanceof Error?e.message:'unavailable');return null;}finally{setBusy(false);}}
 async function invite(target?:Member){const d=await act({action:'invite',store,target:target?.id});if(d?.token){const url=`${location.origin}/#invite=${d.token}`;setLink(url);setQr(await QRCode.toDataURL(url,{width:280,margin:2,color:{dark:'#241b18',light:'#ffffff'}}));setInfo(target?t(`恢复账户：${target.name}`,`Recover account: ${target.name}`):t('新成员注册邀请','New member invitation'));}}
 const allowed=members.filter(m=>m.id!==user.id&&m.role>user.role);
 return <main className="workspace"><div className="page-heading"><div><p className="eyebrow">TEAM & ACCESS</p><h1>{t('账户管理','Team management')}</h1></div><span className="pill">{roleLabels[user.role][lang==='zh'?0:1]}</span></div>{error&&<div className="notice error" role="alert">{errorText(error,lang)}</div>}
 {user.role===0&&<section className="card"><div className="setting-row"><div><h2>{t('启用二维码注册验证','Require QR invitation')}</h2><p className="muted">{t('默认关闭。开启后，新成员及未验证设备需要邀请；现有数据保留。','Off by default. When enabled, new members and unverified devices need an invitation. Existing records are kept.')}</p></div><Switch aria-label={t('启用二维码注册验证','Require QR invitation')} checked={required} disabled={busy} onCheckedChange={enabled=>{if(confirm(enabled?t('开启后，未验证成员需要上级恢复邀请才能再次进入。确定开启？','Unverified members will need a supervisor recovery invitation. Enable?'):t('关闭后，普通成员可仅凭英文名进入。确定关闭？','Ordinary unverified members may enter by name only. Disable?')))void act({action:'settings',enabled});}}/></div><p className="pill">{required?t('已开启','Enabled'):t('已关闭 · 英文名直接进入','Disabled · name-only entry')}</p></section>}
 <div className="team-grid"><section className="card"><h2>{t('邀请下一级成员','Invite the next level')}</h2><p className="muted small-note">{t('邀请会绑定账户级别、直属领导和门店。二维码 24 小时有效，仅可用一次。','Invitations bind role, supervisor and store. Each QR expires in 24 hours and can be used once.')}</p>{user.role===0&&<label className="detail">{t('门店名称','Store name')}<input value={store} maxLength={100} onChange={e=>setStore(e.target.value)} placeholder={t('例如 London Store','e.g. London Store')}/></label>}<button className="primary detail" disabled={busy} onClick={()=>void invite()}>{t('生成邀请二维码','Generate invitation QR')} · {roleLabels[user.role+1][lang==='zh'?0:1]}</button></section>{qr&&<section className="card qr-card"><h2>{info}</h2><img src={qr} width="240" height="240" alt={t('一次性邀请二维码','One-time invitation QR')}/><a href={link} target="_blank" rel="noreferrer">{t('打开邀请链接','Open invitation link')}</a><button className="outline" onClick={()=>void navigator.clipboard.writeText(link).catch(()=>setError('unavailable'))}>{t('复制邀请链接','Copy invitation link')}</button></section>}</div>
 <section className="card"><h2>{t('我的管理范围','My managed members')}</h2><Table><TableHeader><TableRow>{[t('英文名','Name'),t('等级','Role'),t('门店 / 直属领导','Store / supervisor'),t('状态','Status'),t('操作','Actions')].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{allowed.map(m=><TableRow key={m.id}><TableCell>{m.name}</TableCell><TableCell>{roleLabels[m.role][lang==='zh'?0:1]}</TableCell><TableCell>{m.store||'—'}<div className="muted">{members.find(x=>x.id===m.leader_id)?.name||'—'}</div></TableCell><TableCell>{m.active?t('启用','Active'):t('停用','Disabled')} · {m.verified?t('已验证','Verified'):t('简易注册','Name-only')}</TableCell><TableCell><div className="row-actions"><button disabled={busy||!m.active} onClick={()=>void invite(m)}>{t('恢复 / 绑定设备','Recover / link device')}</button><button disabled={busy} onClick={()=>{const n=prompt(t('修改英文名','Change English name'),m.name);if(n)void act({action:'rename',id:m.id,name:n});}}>{t('改名','Rename')}</button><button disabled={busy} onClick={()=>{if(confirm(t(`${m.active?'停用':'启用'} ${m.name}？`,`Change status for ${m.name}?`)))void act({action:'active',id:m.id,active:!m.active});}}>{m.active?t('停用','Disable'):t('启用','Enable')}</button>{user.role===0&&m.role===3&&<button disabled={busy} onClick={()=>{const n=prompt(t('输入直属店员英文名（2级）','Enter the team lead’s name (level 2)'));if(!n)return;const leader=members.find(x=>x.role===2&&x.name.toLowerCase()===n.trim().toLowerCase());if(leader)void act({action:'assign',id:m.id,leaderId:leader.id});else setError('notFound');}}>{t('指定上级','Assign lead')}</button>}{m.role===3&&<button disabled={busy} onClick={()=>{const n=prompt(t('合并到哪个成员？请输入英文名。此账户将停用，记录转入目标账户。','Merge into which member? Enter their name. This account will be disabled and records transferred.'));if(!n)return;const dest=allowed.find(x=>x.role===3&&x.active&&x.id!==m.id&&x.name.toLowerCase()===n.trim().toLowerCase());if(dest&&confirm(t(`将 ${m.name} 合并到 ${dest.name}？`,`Merge ${m.name} into ${dest.name}?`)))void act({action:'merge',id:m.id,into:dest.id});else if(!dest)setError('notFound');}}>{t('合并重复账户','Merge duplicate')}</button>}</div></TableCell></TableRow>)}</TableBody></Table>{!allowed.length&&<p className="empty">{t('暂无下级成员。可生成邀请，或由最高管理员分配成员。','No members yet. Generate an invitation or ask the owner to assign members.')}</p>}</section>
 <section className="card"><h2>{t('我发出的邀请','Invitations I issued')}</h2><Table><TableHeader><TableRow>{[t('角色','Role'),t('门店','Store'),t('截止时间','Expires'),t('状态','Status'),t('操作','Actions')].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{invitations.map(i=><TableRow key={i.hash}><TableCell>{roleLabels[i.role][lang==='zh'?0:1]}</TableCell><TableCell>{i.store}</TableCell><TableCell>{new Date(i.expires).toLocaleString(lang==='zh'?'zh-CN':'en-GB')}</TableCell><TableCell>{i.used_by?t('已使用','Used'):i.revoked?t('已撤销','Revoked'):i.expires<Date.now()?t('已过期','Expired'):t('待使用','Pending')}</TableCell><TableCell>{!i.used_by&&!i.revoked&&<button className="text-button" disabled={busy} onClick={()=>void act({action:'revokeInvite',hash:i.hash})}>{t('撤销','Revoke')}</button>}</TableCell></TableRow>)}</TableBody></Table></section>
 </main>;
}
