import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {build} from 'esbuild';
const base='http://localhost:5173',stamp=Date.now().toString().slice(-7);
const browser=await chromium.launch({channel:'chrome',headless:true});
const contexts=[];const ctx=async(admin=false)=>{const c=await browser.newContext({locale:'en-GB'});contexts.push(c);if(admin)await c.addCookies([{name:'__sites_local_auth',value:'1',url:base,httpOnly:true}]);return c;};
const post=async(c,path,data,status=200)=>{const r=await c.request.post(base+path,{data,headers:{origin:base}});const d=await r.json();assert.equal(r.status(),status,JSON.stringify(d));return d;};
const root=await ctx(true);const anonymous=await ctx();
try{
 await mkdir('.sites-runtime/qa',{recursive:true});
 assert.equal((await anonymous.request.get(base+'/api/records')).status(),401);
 const rootInfo=await (await root.request.get(base+'/api/access')).json();assert.equal(rootInfo.user.role,0);
 await post(root,'/api/team',{action:'settings',enabled:false});
 const memberCtx=await ctx();const name='Mia'+stamp;const joined=await post(memberCtx,'/api/access',{action:'register',name});assert.equal(joined.user.role,3);
 await post(anonymous,'/api/access',{action:'register',name:' '+name.toUpperCase()+' '},409);
 await post(anonymous,'/api/access',{action:'register',name:'<script>'},400);
 assert.equal((await memberCtx.request.get(base+'/api/team')).status(),403);
 await post(memberCtx,'/api/team',{action:'settings',enabled:true},403);
 const page=await memberCtx.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.getByRole('heading',{name:'Field experiment'}).waitFor();await page.getByRole('button',{name:'New session',exact:true}).first().click();
 await page.getByRole('button',{name:'s1a SE plus',exact:true}).click();await page.getByRole('button',{name:'Save & next step',exact:true}).click();await page.getByRole('button',{name:'s23 W plus',exact:true}).click();await page.getByRole('tab',{name:'Step 1',exact:true}).click();await page.getByRole('button',{name:'s1a SE plus',exact:true}).click();
 await page.waitForTimeout(1200);await page.reload();await page.getByRole('heading',{name:'Field experiment'}).waitFor();assert.equal(await page.locator('.counter strong').first().innerText(),'2');
 await memberCtx.setOffline(true);await page.getByRole('button',{name:'s1a SE plus',exact:true}).click();assert.equal(await page.locator('.counter strong').first().innerText(),'3');await memberCtx.setOffline(false);await page.waitForTimeout(1600);
 let data=await (await memberCtx.request.get(base+'/api/records')).json();assert.equal(data.records.length,1);assert.equal(data.records[0].s1a.SE,3);assert.equal(data.records[0].s23.W,1);const recordId=data.records[0].id;
 await page.getByRole('button',{name:'Records',exact:true}).click();await page.getByRole('heading',{name:'My history'}).waitFor();assert.equal(await page.getByRole('button',{name:'Team management'}).count(),0);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export Excel'}).click();await(await download).saveAs('.sites-runtime/qa/member.xlsx');
 await page.getByRole('button',{name:'中文',exact:true}).click();await page.getByRole('heading',{name:'我的历史记录'}).waitFor();
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'.sites-runtime/qa/member-mobile.png',fullPage:true});
 const managerInvite=await post(root,'/api/team',{action:'invite',store:'Test Store '+stamp});const manager=await ctx();const managerInfo=await post(manager,'/api/access',{action:'register',name:'Alex'+stamp,token:managerInvite.token});assert.equal(managerInfo.user.role,1);
 await post(anonymous,'/api/access',{action:'register',name:'Replay'+stamp,token:managerInvite.token},400);
 const leadInvite=await post(manager,'/api/team',{action:'invite'});const lead=await ctx();const leadInfo=await post(lead,'/api/access',{action:'register',name:'Sam'+stamp,token:leadInvite.token});assert.equal(leadInfo.user.role,2);
 const tempInvite=await post(lead,'/api/team',{action:'invite'});const temp=await ctx();const tempInfo=await post(temp,'/api/access',{action:'register',name:'Jo'+stamp,token:tempInvite.token});assert.equal(tempInfo.user.role,3);assert.equal(tempInfo.user.leader_id,leadInfo.user.id);
 await post(anonymous,'/api/access',{action:'login',name:managerInfo.user.name},403);
 const otherInvite=await post(root,'/api/team',{action:'invite',store:'Other Store '+stamp});const otherManager=await ctx();await post(otherManager,'/api/access',{action:'register',name:'Other'+stamp,token:otherInvite.token});
 await post(otherManager,'/api/team',{action:'rename',id:leadInfo.user.id,name:'Hijack'},403);
 await post(lead,'/api/team',{action:'active',id:managerInfo.user.id,active:false},403);
 await post(root,'/api/team',{action:'assign',id:joined.user.id,leaderId:leadInfo.user.id});
 const managed=await(await manager.request.get(base+'/api/records')).json();assert(managed.records.some(r=>r.id===recordId));
 const unrelated=await(await otherManager.request.get(base+'/api/records')).json();assert(!unrelated.records.some(r=>r.id===recordId));
 const deny=await otherManager.request.put(base+'/api/records',{headers:{origin:base},data:{record:data.records[0],revision:data.records[0].revision,mutation:crypto.randomUUID()}});assert.equal(deny.status(),403);
 await post(root,'/api/team',{action:'settings',enabled:true});
 assert.equal((await memberCtx.request.get(base+'/api/records')).status(),401);
 await post(anonymous,'/api/access',{action:'register',name:'NoInvite'+stamp},403);
 await post(anonymous,'/api/access',{action:'login',name},403);
 const recovery=await post(lead,'/api/team',{action:'invite',target:joined.user.id});const recovered=await ctx();const recoveredInfo=await post(recovered,'/api/access',{action:'register',name,token:recovery.token});assert.equal(recoveredInfo.user.id,joined.user.id);
 data=await(await recovered.request.get(base+'/api/records')).json();assert(data.records.some(r=>r.id===recordId));
 await post(lead,'/api/team',{action:'active',id:joined.user.id,active:false});assert.equal((await recovered.request.get(base+'/api/records')).status(),401);
 const unused=await post(lead,'/api/team',{action:'invite'});const team=await(await lead.request.get(base+'/api/team')).json();const recent=team.invitations.find(i=>i.expires===unused.expires);await post(lead,'/api/team',{action:'revokeInvite',hash:recent.hash});await post(anonymous,'/api/access',{action:'inspect',token:unused.token},400);
 await post(root,'/api/team',{action:'settings',enabled:false});
 const adminPage=await root.newPage();await adminPage.goto(base);await adminPage.getByRole('button',{name:'Team management'}).click();await adminPage.getByRole('switch',{name:'Require QR invitation'}).waitFor();assert.equal(await adminPage.getByRole('switch').getAttribute('aria-checked'),'false');
 await adminPage.getByLabel('Store name').fill('London');await adminPage.getByRole('button',{name:/Generate invitation QR/}).click();await adminPage.getByAltText('One-time invitation QR').waitFor();
 await adminPage.screenshot({path:'.sites-runtime/qa/admin-desktop.png',fullPage:true});assert.deepEqual(errors,[]);
 await build({entryPoints:['lib/excel.ts','lib/records.ts'],outdir:'.sites-runtime/qa/lib',bundle:true,platform:'node',format:'esm',outExtension:{'.js':'.mjs'}});const {workbook}=await import('../.sites-runtime/qa/lib/excel.mjs');await writeFile('.sites-runtime/qa/bilingual.xlsx',workbook(data.records,'en'));
 console.log('PASS: name entry, case-insensitive duplicates, same-device persistence, mobile fit, bilingual UI, step backfill, offline saving, Excel download, hierarchy 0→1→2→3, scope enforcement, manager impersonation denial, QR on/off, one-use invitation, device recovery, disabled sessions, revoked invitations, admin UI.');
}finally{await post(root,'/api/team',{action:'settings',enabled:false});await browser.close();}
